# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-wordpress}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland", "Adam Stacoviak", "Pepijn de Vos"]
  s.date = %q{2010-12-24}
  s.description = %q{Helps you create generic WordPress themes and Thematic child themes}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "build.sh",
    "compass-wordpress.gemspec",
    "compass-wordpress/stylesheets/_compass-wordpress.sass",
    "compass-wordpress/stylesheets/layouts/2c-l-fixed.sass",
    "compass-wordpress/stylesheets/layouts/2c-r-fixed.sass",
    "compass-wordpress/stylesheets/layouts/3c-fixed.sass",
    "compass-wordpress/stylesheets/layouts/3c-r-fixed-primary.sass",
    "compass-wordpress/stylesheets/layouts/3c-r-fixed.sass",
    "compass-wordpress/stylesheets/styles/18px.sass",
    "compass-wordpress/stylesheets/styles/21px.sass",
    "compass-wordpress/stylesheets/styles/classic.sass",
    "compass-wordpress/stylesheets/styles/default.sass",
    "compass-wordpress/stylesheets/styles/images.sass",
    "compass-wordpress/stylesheets/styles/plugins.sass",
    "compass-wordpress/stylesheets/styles/reset.sass",
    "compass-wordpress/stylesheets/styles/typography.sass",
    "compass-wordpress/templates/project/functions.php",
    "compass-wordpress/templates/project/manifest.rb",
    "compass-wordpress/templates/project/readme.txt",
    "compass-wordpress/templates/project/screen.sass",
    "compass-wordpress/templates/project/style.css",
    "lib/compass-wordpress.rb"
  ]
  s.homepage = %q{http://github.com/pengwynn/compass-wordpress}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Compass extenstion for creating WordPress themes using Sass}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<compass>, [">= 0.10.6"])
    else
      s.add_dependency(%q<compass>, [">= 0.10.6"])
    end
  else
    s.add_dependency(%q<compass>, [">= 0.10.6"])
  end
end

