# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-wordpress}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wynn Netherland", "Adam Stacoviak"]
  s.date = %q{2009-11-05}
  s.description = %q{}
  s.email = %q{wynn.netherland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/compass-wordpress.rb",
     "lib/wordpress/compass_extension.rb",
     "sass/thematic/_2c_r_fixed.sass",
     "sass/thematic/_images.sass",
     "sass/thematic/_plugins.sass",
     "sass/thematic/_typography.sass",
     "templates/project/css/screen.css",
     "templates/project/manifest.rb",
     "templates/project/readme.txt",
     "templates/project/sass/screen.sass",
     "templates/project/style.css",
     "templates/thematic/css/screen.css",
     "templates/thematic/functions.php",
     "templates/thematic/manifest.rb",
     "templates/thematic/readme.txt",
     "templates/thematic/sass/screen.sass",
     "templates/thematic/style.css"
  ]
  s.homepage = %q{http://github.com/pengwynn/compass-wordpress}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Compass plugin for creating WordPress themes using Sass}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<compass>, ["~> 0.8.17"])
    else
      s.add_dependency(%q<compass>, ["~> 0.8.17"])
    end
  else
    s.add_dependency(%q<compass>, ["~> 0.8.17"])
  end
end

